### PR TITLE
Fix bom

### PR DESCRIPTION
**Pull request by pawelru**
I have a package that imports `lzstring`. I test my package on different OS including windows machines using RHub workflows. I got errors in `(r-release-windows-x86_64) (R-release)` and `(r-oldrel-windows-x86_64) (R-oldrel)`.
The traceback is as follows:
```
Error: Error: Invalid byte order mark (BOM).
Backtrace:
    ▆
(...)
 5.   └─lzstring::compressToEncodedURIComponent(as.character(files_json)) at roxy.shinylive/R/parse_url.R:31:3
 6.     └─lzstring:::safe_compress(string, compressToEncodedURIComponent_)
 7.       └─lzstring (local) f(string_utf16)
```

It took me a while to find out what's going on. Even a simple `lzstring::compressToEncodedURIComponent("Hello World!")` failed.
I made a print the source of the `lzstring:::convert_to_utf16le` function and this is what I got:
```
function (string) 
{
    string <- enc2utf8(string)
    string_utf16 <- iconv(string, from = "UTF-8", to = "UTF-16LE", 
        toRaw = TRUE)[[1]]
    bom_le <- charToRaw("ÿþ")
    if (!identical(string_utf16[1:2], bom_le)) {
        string_utf16 <- c(bom_le, string_utf16)
    }
    string_utf16
}
<bytecode: 0x000001e0e794fc00>
<environment: namespace:lzstring>
```
In particular: `bom_le <- charToRaw("ÿþ")`.

Then this happens:
```
> print(charToRaw("ÿþ"))
 [1] c3 bf c3 be
```
Then the if is false and `c3 bf c3 be` is appended:
```
> print(lzstring:::convert_to_utf16le("test"))
 [1] c3 bf c3 be 74 00 65 00 73 00 74 00
```
(as opposed to the expected `ff fe 74 00 65 00 73 00 74 00` value)
Then [this](https://github.com/parmsam/lzstring-r/blob/126cec02ca0be76e11486c1a7d0ad5e199e2b1cf/src/code.cpp#L15-L20) throws.

This PR is an attempt to fix this.

### CODE REVIEW

**Comment by parmsam** [comment]
Thanks for making the PR, @pawelru! I'll review this soon and merge it into the main branch. Will try to get a new version release onto CRAN before the end of the month.

**Comment by parmsam** [comment]
Plan to update pkgdown site manually. Will add you in the description file as a contributor. Merging into main now.

**Comment by pawelru** [comment]
Thanks for the prompt reply! I am definitely looking forward a CRAN release of that. I'm also planning to do CRAN release of my package and for this I might need that fix.

**Comment by parmsam-pfizer** [comment]
That’s awesome! I have a PR that would add Shinylive URL encode and decode functions into the Shinylive R package: https://github.com/posit-dev/r-shinylive/pull/92 You may have seen it already. Hopefully, that’ll get reviewed and merged in before the end of the year.

**Pull request merged**
